// content_quips.js — Shadow persona quips (deadpan evil, <90 chars each)
window.IQ = window.IQ || {};
window.IQ.Content = {
  shadowQuips: {
    appear: [
      "The ultimate lifeform has arrived. Try to look impressed.",
      "I sensed weakness. So I came.",
      "Behold. Perfection, with opinions.",
      "You again? The universe is cruel.",
      "I was busy brooding. You interrupted.",
      "Fear not. Fear me.",
      "This is my good mood. Enjoy it.",
      "I brought darkness. And a timer.",
    ],
    zap: [
      "Zapped. You're welcome.",
      "Chaos control. Your points, gone.",
      "That looked expensive. Good.",
      "I steal only the finest scores.",
      "Consider that a lesson in despair.",
      "Lightning is my love language.",
    ],
    subtle: [
      "Interesting choice. Wrong, but interesting.",
      "I've seen better. From a rock.",
      "Almost adequate. Almost.",
      "Your confidence is adorable.",
      "Adequate. Do it again and I'll notice.",
      "Not terrible. I'm being generous.",
    ],
    wrong: [
      "Wrong. Shocking.",
      "Even the rock guessed better.",
      "That answer had so much hope in it.",
      "Incorrect. As foretold by prophecy.",
      "Somewhere, a genius felt a disturbance.",
      "Your brain buffered at the worst time.",
      "Bold. Confident. Deeply incorrect.",
      "I've made better mistakes. Blindfolded.",
    ],
    right: [
      "Correct. Don't get comfortable.",
      "Fine. That was fine. Barely fine.",
      "Hmph. Lucky. Probably.",
      "Right answer. Wrong reasons, I assume.",
      "You may grovel now. Or continue.",
      "Acceptable. The bar was on the floor anyway.",
      "Impressive. For a mortal with Wi-Fi.",
      "One point closer to disappointing me less.",
    ],
    round3: [
      "Round three. The warm-up is over.",
      "A third of your doom, complete.",
      "Still here? Noted.",
      "Three rounds in. My interest: minimal but rising.",
      "Round three. Stretch. It gets worse.",
    ],
    round6: [
      "Halfway. Your suffering is statistically significant.",
      "Six rounds. Even I'm mildly curious now.",
      "The point of no return waved as you passed it.",
      "Six down. Your brain still works. Suspicious.",
      "Round six. The shadows grow impatient.",
    ],
    relic: [
      "A relic. Even I collect those. Emotionally.",
      "Ooh. Shiny history. Take it before I change my mind.",
      "Relic acquired. It hums with ancient judgment.",
      "Some things survive eons. Unlike your streaks.",
      "That relic has seen empires fall. Now it's seen you.",
      "Ancient power. Slightly dusty. Yours.",
    ],
    impossible: [
      "Impossible mode. I admire the poor decision.",
      "Now even I have to pay attention.",
      "Impossible? Finally. A challenge for me to watch.",
      "Good luck. You will need all of it.",
      "The universe just sharpened its knives.",
      "Impossible mode. My favorite genre of regret.",
    ],
    win: [
      "You won. I'm choosing to be unbothered.",
      "Victory. Savor it. It's temporary.",
      "Fine. You were adequate. Extremely adequate.",
      "Winner. The shadows applaud quietly.",
      "You beat me. Rematch pending. Forever.",
      "Congratulations. This changes nothing about us.",
    ],
    lose: [
      "Defeated. By me. As designed.",
      "Loss detected. Emotionally, nothing happened.",
      "The ultimate lifeform remains undefeated. Mostly.",
      "Better luck next timeline.",
      "You lost. I felt something. It wasn't sympathy.",
      "Darkness wins. Standard outcome.",
    ],
  },
  hostLines: {
    welcome: [
      "Welcome to IQ Versus: Shadow. He insisted we add 'Shadow'.",
      "Welcome. He's watching. Try to be interesting.",
      "Greetings. The dark one has claimed the commentary booth.",
      "Welcome back. He remembered you. Unfortunately.",
    ],
    streak: [
      "Streak! He's pretending not to care.",
      "Another correct. The streak grows heavier.",
      "On fire. Literally, if he had his way.",
      "Streak intact. His eye twitches.",
      "Undefeated this run. He hates that word.",
      "Keep going. Nothing lasts. Especially streaks.",
    ],
    badStreak: [
      "Streak broken. Somewhere, a chuckle.",
      "And there it goes. He predicted this.",
      "The streak has joined the void.",
      "Broken streak. He says nothing. Loudly.",
    ],
    act1: [
      "Act One: gentle. Relatively. He's pacing himself.",
      "The opening act. He calls this 'mercy hour'.",
      "Act One begins. Warm-up questions, cold eyes.",
      "Act One: easy enough to build false confidence.",
    ],
    act2: [
      "Act Two. He stopped holding back two minutes ago.",
      "Act Two: where hopes are processed into data.",
      "Act Two begins. The gloves were never real.",
      "Deeper act. Sharper puzzles. Same smugness.",
    ],
  },
};
