// content_prompts.js — evil-flavored puzzle prompts for IQ Battle: Shadow
// Shown above boards. Each <60 chars. window.IQ.Prompts
(function () {
  'use strict';
  var Prompts = {
    matrix: [
      'WHICH FRAGMENT SEALS THE SIGIL?',
      'THE GRID LIES. ONE TILE DOES NOT.',
      'COMPLETE THE PATTERN OR BE CONSUMED.',
      'ONE SHARD COMPLETES THE WARD.',
      'THE VOID DEMANDS THE MISSING CELL.',
      'CHOOSE. THE GRID REMEMBERS.',
      'ONLY ONE FRAGMENT FITS THE SEAL.',
      'FINISH THE GLYPH BEFORE IT FADES.',
      'THE MISSING PIECE HUNGERS.',
      'DISCERN THE LAW. CLAIM THE TILE.',
      'THE SIGIL CRACKS WITHOUT ITS CORE.',
      'READ THE GRID. OBEY THE RULE.',
      'ONE CELL STANDS BETWEEN YOU AND DOOM.',
      'THE PATTERN IS WATCHING.',
      'SEAL THE MATRIX. NO SECOND CHANCE.',
      'EVERY ROW WHISPERS THE SAME SECRET.',
      'FIND THE TRUTH HIDDEN IN THE TILES.',
      'THE LAST CELL DECIDES YOUR FATE.',
      'UNLOCK THE GRID\u2019S DARK LOGIC.',
      'A BROKEN WARD AWAITS ITS KEY.',
      'THE COLUMNS CONSPIRE. DECODE THEM.',
      'NO MERCY FOR A MISPLACED TILE.'
    ],
    sequence: [
      'WHAT COMES NEXT IN THE CURSE?',
      'PREDICT THE NEXT BLOW.',
      'THE CHAIN CONTINUES. COMPLETE IT.',
      'NEXT LINK IN THE DARK RITE?',
      'FORESEE THE SHAPE TO COME.',
      'THE SEQUENCE HUNGERS FOR ITS END.',
      'CONTINUE THE PROCESSION.',
      'STAY ONE STEP AHEAD OF THE SHADOW.',
      'DIVINE THE NEXT TURN OF THE SCREW.',
      'THE PATTERN MARCHES ON. LEAD IT.',
      'NAME THE NEXT GLYPH IN LINE.',
      'EXTEND THE INCANTATION.',
      'THE RITUAL PAUSES. WHAT FOLLOWS?'
    ],
    oddone: [
      'ONE TILE BETRAYS THE COVEN.',
      'SPOT THE IMPOSTOR AMONG THE SIGILS.',
      'ONE DOES NOT BELONG. EXILE IT.',
      'THE OUTSIDER HIDES IN PLAIN SIGHT.',
      'FIND THE TILE THAT BROKE THE RITE.',
      'ONE SHAPE DEFIES THE LAW.',
      'HUNT THE HERETIC CELL.',
      'ODD ONE OUT. SHOW NO MERCY.',
      'ONE PIECE WAS NEVER INVITED.',
      'EXPOSE THE FORGED FRAGMENT.',
      'THE REBEL TILE MUST FALL.',
      'SOMETHING IS WRONG HERE. FIND IT.'
    ],
    corrupt: [
      'CORRUPTION SPREADS. FIND THE FLAW.',
      'RESTORE WHAT THE ROT DESTROYED.',
      'THE HEX LEFT ITS MARK. UNDO IT.',
      'REPAIR THE DEFILED PATTERN.',
      'DARKNESS EDITED THE GRID. FIX IT.',
      'PURGE THE TAINT FROM THESE TILES.',
      'THE SEAL IS BROKEN. REBUILD IT.',
      'TRACE THE CORRUPTION TO ITS SOURCE.',
      'CLEANSE THE BOARD OR PERISH.',
      'A VIRUS HAUNTS THE CELLS. ERASE IT.',
      'UNRAVEL THE WARPED WEAVE.',
      'EVIL REWROTE THE RULES. RIGHT THEM.'
    ]
  };

  if (!window.IQ) window.IQ = {};
  window.IQ.Prompts = Prompts;
})();
